travis:
  secure:
    BINSTAR_TOKEN: dwhiJxon0EUf8BxEeg4mCoUGIyBriXQzXEsSw3+kit1uNQsqpfKabaR44k7qqS6maxz+EDzXurT20wQXZaGTp6NFurPkSCN1f+abu5otOKDpHxPioVSYMlfMeORFfrOzv+jNAJt5NDiigYXwZkzmFCKYYVsd7HcJwrJyH4Rq8kUu8VNLijwQI0pCx+gMk2mA6FvgUb3QlFfTvD4AwoI0cSCmZam8kKdsd2CJo0XxA+Zo6lELUeIIib+kfjZ4VwxYa1fWr2YhFqX7o/Fdy4znox98KznPMGsmprhc4OtTF1Fp0axmnZ/LWBLnqmLBkD5KtGmiYAYMWL13PktvN5jWC4hDRXk9EP0RpRypQhTe8Unki/f+wfSDjn52d6MFYPIHcpRqL+VOHEkuTHOLaEurVJ4uRZhsGMTnC3pQz5SvelnMHV+gPNl8STvKOg9bDk8OXiJLHV/Ka4K718eKDljrDvQNo7VQ+ZWebYvPCLBcknl+RFOCEeGod0s6dk25ogAxQEgQRZdNY+cCo3zZS4ELElRHtDEoZcm1A2/l2hD/iIIqNY4NRy8CgDuW8zRnKbxbcr8KNIbjbQvvpuhix3IoxetupLDbB1bQQ1g0Y8HuKe0JQvA4cCkVF3p7y3KVghz1yA00UVyduYS/hPxgYxyqObW4xQHBvO0EufK9iDp77eU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
